// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gozmvdbeolbwqfbgpytt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvem12ZGJlb2xid3FmYmdweXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDkzMzMsImV4cCI6MjA1OTkyNTMzM30.eOiiyi37GORycLCxHpOaA8AsJprbo6UNo686RotR4BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);